### ISSUE TITLE
Which java version?

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#11]
One page mentions JDK 9+ (https://github.com/goxr3plus/XR3Player/blob/master/CONTRIBUTING.md), the readme says [JDK 10.0.2+]. 

I tried with JDK 11.0.1, because I have it on my machine. To get that to work, I had to add a couple of dependencies in the pom.xml file:

		
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>11.0.2</version>
		</dependency>

		
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-fxml</artifactId>
			<version>11.0.2</version>
		</dependency>

What do you use for development?

**Comment by goxr3plus** [comment]
Yes yes we must transder it to Java 11

**Comment by goxr3plus** [comment]
You must use JAVA 10 :)

**Comment by goxr3plus** [comment]
Really it fully worked just by added those dependencies :)?

**Comment by goxr3plus** [comment]
Can you help me on completely transferring it to Java 11 ++

**Comment by HelgeStenstrom** [comment]
There is at least one more missing dependency, I found this morning. javafx-media.

**Comment by HelgeStenstrom** [comment]
Maybe I can help you a bit on the road to Java 11. I have very limited experience myself, being a professional Java developer for only three months, using a Java 1.8 at work. I’m here to learn, and found your project because I have some vague ideas about a sound processing app I want to make, and I searched for inspirational examples were oscilloscope and javafx were mentioned in the same project.

**Comment by HelgeStenstrom** [comment]
Actually, when I switched from Java 11 to Java 10, the DJDiscResizer started. I cannot say if it works as intended, but at least there is a GUI, and no error messages in the console.

**Comment by goxr3plus** [comment]
Nice to hear :)?

**Comment by goxr3plus** [comment]
Let's continue this issue on #10
