### ISSUE TITLE
Is any main class/method expected to work on Mac?

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#12]
I found three main methods, that I tried to run, but all three fails with an exception.

DJDiscResizer fails with InvocationTargetException

Main fails with InvocationTargetException

MicrophonePCMAnalyzerTest brings up a window (which is empty), but repeatedly throws an NullPointerException 

Perhaps some of these are caused by the way I run the program. I'm using IntelliJ IDEA, and start these three classes from the IDE. Not sure which details about the runtime configuration that could be useful.

**Comment by goxr3plus** [comment]
Hm that's strange oh my, i don't have a MAC, can you send me the stacktrace please :)?

**Comment by goxr3plus** [comment]
I merged your Pull Request :)
