### ISSUE TITLE
Odd package name hierarchy

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#13]
Usually the packet name path looks like a web address in reverse, starting with com. or org. 

 package main.java.com.goxr3plus.xr3player.application

doesn't follow that pattern. It looks like a common directory structure has invaded the package names. The package name above should be com.goxr3plus.xr3player.application, and the root package com should be placed in the directory main/java. In IntelliJ, main/java can be marked as sources root, and there could be a complementary main/test test root directory.

**Comment by goxr3plus** [comment]
How should i change it , like Maven standard directory layout is suggesting that pattern so Maven works correctly by default, correctly me when i am wrong :)

**Comment by HelgeStenstrom** [comment]
Your directory structure is correct. But main.java should not be a part of the package name path. The root package should be com, placed in the directory src/main/java.

**Comment by HelgeStenstrom** [comment]
The image shows the directory and package structure when the project is imported to IntelliJ.
The directory structure looks good.

src is marked as Sources root. It shouldn't.
src/main/java should be the sources root. Then com will be the root package. This change will change the package line of all java files, from `package main.java.com.goxr3plus` into `package com.goxr3plus`.
I also recommend having a src/test/java directory marked as Test Sources Root.
And src/main/resources marked as Resources root. The folders inside the resources hierarchy aren't packages, but they look like packages now.


<img width="409" alt="Skärmklipp 2019-04-21 21 49 23" src="https://user-images.githubusercontent.com/169443/56474809-72228580-647f-11e9-97d6-587514e9800c.png">

**Comment by goxr3plus** [comment]
Thank you for the recommendation, isn't there a setting in the IntelliJ capable of doing it. Let me check again how it looks like in IntelliJ in my machine.

If i am wrong i would like your solution.

**Comment by goxr3plus** [comment]
And yes we need some tests too :). How advanced you are with JavaFX :)?

**Comment by HelgeStenstrom** [comment]
I'm not advanced with JavaFX, but I have made a couple of programs. The largest does some 3D visualization, nothing fancy. That one runs JDK 1.8. 
I have heard about Spring, but I don't know what it can do. There is a dependency injection part of it, which I'm interested in learning about. But dependency injection doesn't need a framework.

**Comment by HelgeStenstrom** [comment]
Here are a couple of links for the standard Maven directory structure.
https://www.baeldung.com/maven-directory-structure
https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

Please remove `/test` from .gitignore. `src/test` is the standard place for unit tests, according to the above descriptions. 
If you have src/tests/java marked as test sources root in IntelliJ, and you are reading a normal production code class, you can do Code --> Generate --> Test..., and a test class will be created for you, in a file below the test root, with the same package as the one you started from. Rather useful.

**Comment by goxr3plus** [comment]
Thank you very much for the linka, i am reading them

**Comment by goxr3plus** [comment]
Please i want you to learn hoe to do pull requests, it's very simple, you fork the repository, do your commits, then come into my repository and there is an option which is called Pull Requests... check on the web hoe to do pull requests in Github... in that way you can contribute as much as you want and maybe i give you full access to XR3Player repo so you can directly commit on it, intead of pull requests  but firstly  i need to see your code experience through Pull Requests :)

**Comment by goxr3plus** [comment]
How should i change pom.xml to make it correct ? Until now i have changed this : 

```
	<build>
		<finalName>XR3Player</finalName>
		<sourceDirectory>src/main/java</sourceDirectory>
              .....
```

**Comment by goxr3plus** [comment]
@HelgeStenstrom  Thank you very much i fixed it in this commit https://github.com/goxr3plus/XR3Player/commit/d867eafe974fa808dc29ead4fe00499ead011c7a 

Changed 210 files lol . Of course using replace all tool from intelliJ and modifying pom.xml .

I am impressed by your knowledge :)

**Comment by HelgeStenstrom** [comment]
Thank for the work!

**Comment by goxr3plus** [comment]
YES boy :)
