### ISSUE TITLE
Filename should end in .flac

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#16]
https://github.com/goxr3plus/XR3Player/blob/365ee651395ad364253fcbbdde1c77f8c1740a10/src/main/java/com/goxr3plus/xr3player/xplayer/microphone/MicAvailabilityChecker.java#L16

because it's a flac file.

Also:

what is the purpose of MicAvailabilityChecker? How do you check that the microphone is actually available? I found the bug because I found the file and couldn't play it. I found out it was a flac file, but I still couldn't play it. Do you run the program, and then play the file, or do you just run the program and be satisfied if it finishes without problems? If so, you don't have to save the file to disc. Use captureAudioToFile(File audioFile) with a file-like object as parameter.

**Comment by goxr3plus** [comment]
Well i added it there for future implementation, i haven't fully tested it :)

**Comment by goxr3plus** [comment]
Please add some titles to the issues so i know when i navigate :)

**Comment by HelgeStenstrom** [comment]
> Please add some titles to the issues so i know when i navigate :)

Didn't I do that?

**Comment by goxr3plus** [comment]
@HelgeStenstrom Yes ouh i didn't saw it for this question, it was morning and i was dizzy lol sry.

**Comment by goxr3plus** [comment]
I am thinking about this right now .

**Comment by goxr3plus** [comment]
ouuuh i remembered this issue today . It doesn't work because i removed the dependency ... :)

I used to have Speech Recognition in XR3Player but it was an experimental feature which i didn't had enough experience to complete it so i left it there for future implementation.

(Google Speech API](https://github.com/goxr3plus/java-google-speech-api)
