### ISSUE TITLE
Java 11 Ready To Go

### ISSUE THREAD

**Issue by goxr3plus** [goxr3plus/XR3Player#17]
@HelgeStenstrom  @TonalidadeHidrica

Here is Java 11 Version => [ Java 11 Branch ](https://github.com/goxr3plus/XR3Player/tree/Java-11) which i have changed everything to be compatible with Java 11 .

I can't run it though ... i don't know what is the problem .

Please help :)!!!!!

**Comment by HelgeStenstrom** [comment]
I'm as new with Java-11 as you are. But I think module-info.java is put in
the wrong place, and that it should be in the source tree, not in the
resource tree.
But it right under src/main/java.
I did so. had to add


requires java.logging;

but got the problems with

Error:java: module XR3Capture reads package
org.tritonus.share.sampled.mixer from both tritonus.all and
tritonus.share

haven't investigated further.


/Helge


Den mån 20 maj 2019 kl 16:54 skrev GOXR3PLUS STUDIO <
notifications@github.com>:

**Comment by goxr3plus** [comment]
Thank you very much i will investigate too :)

**Comment by goxr3plus** [comment]
@HelgeStenstrom  I updated the Java11 branch and removed tritonous-share and also moved module-info.java and added `requires java.logging;` .

Please make a merge and let me know :) .

Don't forget that you can directly commit on the branch Java11 in this repository :)

**Comment by goxr3plus** [comment]
@HelgeStenstrom Resolved all the problems you had => https://github.com/goxr3plus/XR3Player/tree/Java-11 now we have a new problem with `Jave2` dependency and i opened an issue to the [Jave2 Repository](https://github.com/a-schild/jave2/issues/52) .

I am also a collaborator to that repository so i can make changes , tell me if you can help :) .

I am getting more confortable with Java11 and i see XR3Player passing soon in Java11/12/13.

**Comment by goxr3plus** [comment]
@HelgeStenstrom  I died in front of the screen , managed to make it play , though i have disabled web-browser because i get a strange error about reflection which i don't know how to solve yet .

Feel free to try it :) , XR3Player just fully runned on Java 11 .

Please don't forget to add those as VM Parameters => 

``` JAVA
--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix
```
because JFoenix is not fully capable of Java  9 .

**Comment by goxr3plus** [comment]
@HelgeStenstrom  Merged everything to master , now it's oficially running on JDK 11 and soon on JDK 12 and 13.

I have a problem with the Reflections , i can't get it working . It's a trick in order to bypass JxBrowser license , even though i have a license i don't want to bother everytime with a new one .

So i am using Reflection in order to bypass , but on Java 11 i don't know why it throws errors i can't use `Field` and stuff like that :( .

Can you help me ?

Also if you want to run the project please read the instructions .

**Comment by goxr3plus** [comment]
@HelgeStenstrom  We just passed in Java 12 with the latest commit . Ah i can't get that reflection work ... ah Java damnnnn .

And don't want to go again through the procedure of getting a license for JxBrowser .

**Comment by HelgeStenstrom** [comment]
I don't have Java 12 installed. Perhaps I will get it.
What is it that requires Java 12, except the pom.xml file?

**Comment by goxr3plus** [comment]
Inside thr pom inhave added JavaFX 12.

**Comment by HelgeStenstrom** [comment]
So if I change back to Java 11 in the pom.xml file, I can use Java 11?
There is no particular feature of Java 12 that you are using in the project?


Den tis 11 juni 2019 kl 07:22 skrev GOXR3PLUS STUDIO <
notifications@github.com>:

**Comment by goxr3plus** [comment]
Java 12 comes with performance improvements and other stuff. Yes id you
return the pom you can run it with Java 11.

Change every 12 to 11, special care check frok Maven central the latest
JavaFX 11 version I think it's 11.0.2

**Comment by goxr3plus** [comment]
Closing this as done i think .
