### ISSUE TITLE
ColorIndex in Oscilloscope, why?

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#18]
https://github.com/goxr3plus/XR3Player/blob/7e90aa4036d749807dadb58e0457e5dc6eb5e470/src/main/java/com/goxr3plus/xr3player/xplayer/visualizer/geometry/Oscilloscope.java#L139

would be simpler expressed (I haven't tested) as 

```java
colorIndex = colorIndex++ % colorSize;
```

But what it the purpose of updating colorIndex?

**Comment by goxr3plus** [comment]
Oh you are digging into the madness of Visualizer, would you believe me if i tell you i have written this code during 15 hours straight coding :)?

I think inam changing the colors of the line based on something.

I plan to make it a separate library which is not part of XR3Player code, so we will have multiple modules.

**Comment by goxr3plus** [comment]
Did you manage to run XR3Player on Java 11? I am having problems after starting it on making amplitudes work, Jave2 library is not exporting the FFMPEG correctly.

Ah i will fix everything, i watched 11 hours tutorials for Java 9 JPMS modular systen.

**Comment by HelgeStenstrom** [comment]
I haven't really tried yet. I tried and failed before I learned that I have to supply some VM arguments, but haven't done so.

**Comment by goxr3plus** [comment]
Yyes without VM arguments it can not run. By the way installing Java 12 is
like too easy and you don't really have to change anything in IntelliJ.

**Comment by HelgeStenstrom** [comment]
Did you pick Java 12 from Oracle or from https://openjdk.java.net?

**Comment by goxr3plus** [comment]
From Oracle but i think OpenJDK with work too.

**Comment by HelgeStenstrom** [comment]
I did it, have Java 12 now.

**Comment by goxr3plus** [comment]
Glad to hear :) Let me know your opinion when you finally run it :)
