### ISSUE TITLE
What is the calling order (show vs initialize)

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#20]
https://github.com/goxr3plus/XR3Player/blob/7d79f3b4ccca604a34e22e593b2510710580303c/src/main/java/com/goxr3plus/xr3player/controllers/dropbox/DropboxFileContextMenu.java#L49

I wonder about the calling order for the methods initialize() and show() in DropboxFileContextMenu. I would expect initialize() to be called first. What happens then to the field **node**? 

What is that field node used for?

**Comment by goxr3plus** [comment]
initialize() is called as soon as the fxml is ready and is called automatically one time once the object is created.

**Comment by goxr3plus** [comment]
I use show, to make the context menu visible :)

**Comment by HelgeStenstrom** [comment]
Isn't it strange, then, that node is written by show() and read by initialize(). When initialize() is run, the value is null. Was that the intention?

**Comment by goxr3plus** [comment]
That's a pattern in JavaFX you create the calss via constructor and when fxml objects are populated initialize() method is called.

:) Show is always called after initialize()


Let me know if i explain it well enough. I am trying to understand your point.

**Comment by HelgeStenstrom** [comment]
Now I understand this better. What I didn't see from the beginning, is that initialize() defines a callback method that reads **node**, rather than reading **node** itself. So **node** is not read before it's written; it's read when the callback method is called, i.e., when there is an action on the MenuItem **rename**. This callback method is defined before **node** is written the first time, but that is OK.
