### ISSUE TITLE
Project Package Structure Update

### ISSUE THREAD

**Issue by Valkryst** [goxr3plus/XR3Player#3]
Following the [Java standard](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) for package naming/structure, you should rework the src folder as follows.

src -> (com|org|net|etc) -> goxr3plus -> xr3player -> All packages would go here.

**Comment by goxr3plus** [comment]
I will definitely do this very soon thank you :)

**Comment by goxr3plus** [comment]
@Valkryst  Hello :) I have followed the Maven Standard Directory Layouthttp://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html and converted it as requested . 

Can you have a look and tell me if i have done it as it is supposed to ? :) After this i will startardize JavaDoc and move into new features for Java 9.

**Comment by Valkryst** [comment]
Looks good to me.

**Comment by goxr3plus** [comment]
Ok so i close this issue :)
