### ISSUE TITLE
Is vertikal bar a valid character in a command?

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#38]
https://github.com/goxr3plus/XR3Player/blob/e497f1958be8905eb3c20956dd1b616704c5acf7/src/test/java/com/goxr3plus/xr3player/controllers/windows/ConsoleWindowControllerTest.java#L20

Should this test really pass? Is a vertical bar acceptable before the number, or are only plus and minus expected?

**Comment by goxr3plus** [comment]
I know good regex, then i don't use them for sometime and then i become again newbie and need to read what your matcher expression means :)

**Comment by HelgeStenstrom** [comment]
It's not my matcher expression, it's yours. (pattern1 in this case)
"player:|22:aWord" is just a string. It doesn't mean anything, but it might match your matcher expression. 
Well, it does, and I think it should not.

**Comment by HelgeStenstrom** [comment]
I just made a pull request #39  , with unit tests to demonstrate the bug.

**Comment by goxr3plus** [comment]
I can't really understand what is going around that regex.


@HelgeStenstrom Can you please let me now.

1) What was the problem
2) What we are trying to solve
3) Your solution

**Comment by HelgeStenstrom** [comment]
My solution is to remove the vertical bars from the definition of pattern 1, 2 and 3.

**Comment by goxr3plus** [comment]
@HelgeStenstrom :) Sorry if i am not responding very fast, it's just i am all day in work.

I would like to train you to become component leader of this project.

How good is your experience with JavaFX :)?

**Comment by HelgeStenstrom** [comment]
I don’t think I want that position. But I’ll be happy to propose improvements wherever I see opportunities, and where I feel that I can learn things. 

My interest started because I though that your program could provide inspiration to a program of my own. My program will use JavaFx and handle sound. But it has performance problems. And I have only rough ideas about what it should do.

**Comment by goxr3plus** [comment]
We close this issue?
