### ISSUE TITLE
VM arguments ad add-exports

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#43]
The VM arguments, as written in README.md are probably slightly wrong. I don't think there should be an equal sign after add-exports or add-opens. 
See for example: https://javaworklife.wordpress.com/2019/05/20/java11-intellij-running-tests-with-add-exports-in-intellij/ 

So it should be:
--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports javafx.base/com.sun.javafx.event=com.jfoenix
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-exports javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls,
--add-exports javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls

**Comment by goxr3plus** [comment]
Thank you , have you tested that it works like that ?

**Comment by HelgeStenstrom** [comment]
No

tors 11 juli 2019 kl. 14:54 skrev GOXR3PLUS STUDIO <notifications@github.com

**Comment by goxr3plus** [comment]
Okay i tested they work , so the final is this : 

``` JAVA
--add-exports
javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
--add-exports
javafx.controls/com.sun.javafx.scene.control=com.jfoenix
--add-exports
javafx.base/com.sun.javafx.binding=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.stage=com.jfoenix
--add-exports
javafx.base/com.sun.javafx.event=com.jfoenix
--add-exports
javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls,
--add-exports
javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls
```

**Comment by HelgeStenstrom** [comment]
Do you really have newline after --add-exports?

**Comment by goxr3plus** [comment]
Do you really have newline after --add-exports?
IntelliJ putted it automatically for some reason ...

**Comment by goxr3plus** [comment]
Should we close this ?

**Comment by HelgeStenstrom** [comment]
The newlines are removed now, right? If so, close this.
