### ISSUE TITLE
What is the difference between xPlayer 0, 1 and 2?

### ISSUE THREAD

**Issue by HelgeStenstrom** [goxr3plus/XR3Player#44]
https://github.com/goxr3plus/XR3Player/blob/c4a3299f9dd0e2f7c1e44bc8d1a8714a8d99ab98/src/main/java/com/goxr3plus/xr3player/controllers/djmode/DJMode.java#L46-L48

They are different. Or rather; they are subsequently initialized in different ways. 
Can these xPlayers be given more clarifying names?

**Comment by goxr3plus** [comment]
The xPlayer0 is the one in the Main Window , The XPlayer1 and xPlayer2 are the 2 players on the djmode.

**Comment by goxr3plus** [comment]
I must refactor the code  , i have to admit it's very confusing in some parts .

**Comment by goxr3plus** [comment]
XPlayer 0 
https://camo.githubusercontent.com/73e9b0b1131a6a77b857523ceba1a186ce6a44dc/68747470733a2f2f676f787233706c75732e6769746875622e696f2f787233706c617965722e696f2f696d672f787233706c617965722f6d61696e5f6d6f64652e6a7067
XPlayer1 and XPlayer 2
![image](https://user-images.githubusercontent.com/20374208/61052792-cd1ba700-a3f4-11e9-93a8-98fe3170befc.png)

**Comment by goxr3plus** [comment]
I hope this was clear to you so i am closing this issue :)
