### ISSUE TITLE
 error using "All in XR3Player" run configuration

### ISSUE THREAD

**Issue by sildeag** [goxr3plus/XR3Player#86]
Using IntellijIDEA community 2023.1 and Amazon Corretto version 20.

I am getting this error using "All in XR3Player" run configuration.  `java.lang.NullPointerException: Cannot invoke "com.sun.glass.ui.Timer.resume()" because "this.pulseTimer" is null ...`  What am I missing?

**Comment by sildeag** [comment]
Yes.  I added the VM options `--add-exports javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix --add-exports javafx.controls/com.sun.javafx.scene.control=com.jfoenix --add-exports javafx.base/com.sun.javafx.binding=com.jfoenix --add-exports javafx.graphics/com.sun.javafx.stage=com.jfoenix --add-exports javafx.base/com.sun.javafx.event=com.jfoenix --add-exports javafx.graphics/com.sun.javafx.scene=org.controlsfx.controls, --add-exports javafx.graphics/com.sun.javafx.scene.traversal=org.controlsfx.controls`

**Comment by goxr3plus** [comment]
So you have Java 19 and you have added the VM parameters inside the IntelliJ or Eclipse and still error? That's really strange. Have you checked the gif i have on read me?

**Comment by sildeag** [comment]
Yes.  I have checked the gif in the readme and am missing the source code under `assembly`.

**Comment by goxr3plus** [comment]
Are you using windows, mac or Linux and which version of them.

**Comment by sildeag** [comment]
Sorry, I took too long.  I am using Windows 11.  I have been trying to slow down the gif as I have not activated the tool window as shown.

**Comment by sildeag** [comment]
I followed the gif and that made all the difference.

**Comment by goxr3plus** [comment]
I should probably make it like a video too ☺

**Comment by sildeag** [comment]
Thank you for a great application and your help.

**Comment by goxr3plus** [comment]
☺ My pleasure helping the community. I have 15 new mobile apps that i will probably open-source also.
